# Generated by Django 4.0.1 on 2022-01-24 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='form',
            new_name='messages',
        ),
    ]
